coursename=input("enter a course name")
coursetype=input("enter a course type")
courseduration=input("enter a course duration")
coursefees=input("enter a course fees")
f=open("course.txt","a")
f.write(coursename)
f.write(" ")
f.write(coursetype)
f.write(" ")
f.write(courseduration)
f.write(" ")
f.write(coursefees)
f.write(" ")
f.write("\n")
f.close()